# Site settings
exclude: [README.md,example1.md,example2.md]
title: Yi Zhang
email: darcyyizhang@gmail.com
github: yi-zh
# twitter: lena_voita
scholar_id: QAZD5GMAAAAJ
# description: > # this symbol means ignore newlines until "baseurl:"
#     Hi! I'm Lena and here you will find what I do.
baseurl: "" # keep blank unless you're using sub-paths
url: "http://yi-zh.github.io" # the base hostname & protocol for your site
#paginate: 3

# you can also declare arbitrary key-value data here
tof_url_main: "https://minlp.com/home"
tof_url_team: "https://minlp.com/our-team"

# Build settings
markdown: kramdown
